SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) AS 'count'
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY CASE
         WHEN ANIMAL_TYPE = 'Cat' THEN 1
         WHEN ANIMAL_TYPE = 'Dog' THEN 2
         END;